# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: SecTeerApS.SecTeerVulnDetect
PackageVersion: 2.4.2.0
PackageLocale: en-US
Publisher: SecTeer ApS
PackageName: SecTeer VulnDetect
License: Proprietary, see license file for details. Free for Personal / home use.
Copyright: © SecTeer ApS. All rights reserved.
ShortDescription: 'VulnDetect detects and silently updates third party applications on Windows. Use: winget install SecTeerApS.SecTeerVulnDetect --override "/VERYSILENT /email=your@email.tld"'
ManifestType: defaultLocale
ManifestVersion: 1.2.0

